kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.project_name }}-{{ .Release.Namespace }}-admin
rules:
- apiGroups: [""]
  resources: ["*"] # All resources can be accessed.
  verbs: ["*"] # All operations can be performed.