kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.project_name }}-{{ .Release.Namespace }}-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.project_name }}-cd
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.project_name }}-{{ .Release.Namespace }}-admin
  apiGroup: rbac.authorization.k8s.io